-- Base de données : `reconnaisancefacial`

CREATE DATABASE reconnaisancefacial;
USE reconnaisancefacial;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Table 1 : Structure de la table `departement`
--

DROP TABLE IF EXISTS `departement`;
CREATE TABLE IF NOT EXISTS `departement` (
  `ID_DEPARTEMENT` int NOT NULL AUTO_INCREMENT,
  `NOM_DEPARTEMENT` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `CHEF_DEPARTEMENT` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DEPARTEMENT`),
  UNIQUE KEY `UNQ_NOM_DEPT` (`NOM_DEPARTEMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Table 2 : Structure de la table `etudiant`
--

DROP TABLE IF EXISTS `etudiant`;
CREATE TABLE IF NOT EXISTS `etudiant` (
  `CNE_MASSAR` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `ID_DEPARTEMENT` int NOT NULL,
  `NOM` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `PRENOM` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `SEX` varchar(3) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TELEPHONE` varchar(15) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `MAIL` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `OPTIONS` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ANNEE_ACADEMIQUE` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SEMESTRE` int DEFAULT NULL,
  PRIMARY KEY (`CNE_MASSAR`),
  KEY `FK_ETUDIANT_DEPARTEMENT` (`ID_DEPARTEMENT`),
  CONSTRAINT `FK_ETUDIANT_DEPARTEMENT` FOREIGN KEY (`ID_DEPARTEMENT`) REFERENCES `departement` (`ID_DEPARTEMENT`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Table 3 : Structure de la table `image`
--

DROP TABLE IF EXISTS `image`;
CREATE TABLE IF NOT EXISTS `image` (
  `ID_IMAGE` int NOT NULL AUTO_INCREMENT,
  `CNE_MASSAR` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `IMAGE` longblob NOT NULL,
  PRIMARY KEY (`ID_IMAGE`),
  KEY `FK_IMAGE_ETUDIANT` (`CNE_MASSAR`),
  CONSTRAINT `FK_IMAGE_ETUDIANT` FOREIGN KEY (`CNE_MASSAR`) REFERENCES `etudiant` (`CNE_MASSAR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Table 4 : Structure de la table `presence`
--

DROP TABLE IF EXISTS `presence`;
CREATE TABLE IF NOT EXISTS `presence` (
  `ID_PRESENCE` int NOT NULL AUTO_INCREMENT,
  `DATE_PRESENCE` date NOT NULL,
  `HEURE` time NOT NULL,
  `STATUT` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `CNE_MASSAR` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID_PRESENCE`),
  KEY `FK_PRESENCE_ETUDIANT` (`CNE_MASSAR`),
  CONSTRAINT `FK_PRESENCE_ETUDIANT` FOREIGN KEY (`CNE_MASSAR`) REFERENCES `etudiant` (`CNE_MASSAR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Table 5 : Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `ID_USER` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `PASSWORD` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE KEY `UNQ_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;